apiVersion: v1
kind: PersistentVolume
metadata:
  name: vpro-pv
spec:
  capacity:
    storage: 2Gi  
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  
  hostPath:
    path: /root/java-vpro  

